### ISSUE TITLE
"next" version checklist

### ISSUE THREAD

**Issue by zoton2** [zoton2/nodecg-vue-ts-template#16]
Currently rewriting this template, mainly to upgrade to Vue3 and improve the building. Not all points that need to be done are listed below, but important things to remember are.

- [x] Include Quasar for material design on dashboard panels.
  - [x] Make sure background is not replaced with Quasar's dark mode.
- [x] Add ESLint support.
- [x] Add support for replicants in the browser, probably using [nodecg-vue-composable](https://www.npmjs.com/package/nodecg-vue-composable).
- [x] Proper TSConfig files for:
  - [x] Extension
  - [x] Browser
- [x] Write basic README.
- [x] Typescript checking for browser building.
- [x] Make sure VSCode integrations work for all browser/extension files.
- [x] Use helper library for NodeCG types.
