### ISSUE TITLE
v3.0.0 checklist

### ISSUE THREAD

**Issue by zoton2** [zoton2/nodecg-vue-ts-template#23]
This update is being built upon some work I already did for NodeCG v2 usage but never merged into main. I will be targeting NodeCG v2.3.x which properly supports Node.js v22 (LTS) which means I can properly move to using "ES Modules" (ECMAScript) as the output on the extension builds.

- [x] Overhaul the `tsconfig.json` files and how they work.
- [x] Convert `extension` code to properly build.
- [x] Convert browser based code to properly build.
- [x] Remove `module-alias`/custom paths.
- [x] Add shared file for replicants in browser context.
- [x] Migrate to ESLint v9 and flat configs.
- [x] Add `.vscode` files.
  - [x] `extensions.json`
    - [x] Any other recommended extensions to add?
  - [x] `settings.json`
    - [x] Tweak file nesting patterns for ESLint v9.
- [x] Remove `env.d.ts`?
- [x] ~~Remove `nodecg-cli`, *don't* install `nodecg` and suggest users install it globally (or add it as an optional dependency?)~~
- [x] ~~Add/switch to Sass or SCSS.~~
- [x] Improve type file setup overall.
  - [x] This includes ESLint related things.
  - [x] ~~Do we need a specific `tsconfig.json` setup?~~
- [x] Update `README.md` file.
  - [x] Note why we use `draft-07` JSON schema spec (VSCode).
  - [x] Note (with a link) about additional Quasar configuration.
- [x] Any additional file comments that may be useful for future reference/other users.

**Comment by zoton2** [comment]
Things that I've changed but made a note of to verify I don't have issues with them in real world use-cases:

- [ ] dashboard template having `font-size: unset !important` (which removes Quasar's `14px` font-size setting, and seems to make it `16px`); does this have any side effects with Quasar elements?
- [ ] I have tweaked the Quasar primary colour to match that of the NodeCG primary colour, but need to test the rest of the colours.
